services:
  flask_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flask run --host 0.0.0.0
    volumes:
      - ./:/app:z
    env_file:
      - .env
      - .flaskenv
    environment:
      ENVIRONMENT: DEBUG
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
